robot_base_frame: $(arg frame)base_link

#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.225

inscribed_radius: 0.225
circumscribed_radius: 0.225

obstacle_range: 4.9
raytrace_range: 5.0

observation_sources: scan
scan:
  {
    sensor_frame: $(arg frame)hokuyo_link,
    data_type: LaserScan,
    topic: $(arg namespace)/scan,
    marking: true,
    clearing: true,
  }

obstacle_layer:
  obstacle_range: 4.9 # Needs to be < raytrace_range it seems. Needs to be less than max range to not consider max scan range as obstacle
  raytrace_range: 5.0
  enabled:              true
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space

  observation_sources: scan
  scan:
    sensor_frame: $(arg frame)hokuyo_link,
    data_type: LaserScan,
    topic: $(arg namespace)/scan,
    marking: true,
    clearing: true,

