controllers:
  - name: QuadGapPlannerROS
    type: quad_gap/QuadGapPlannerROS

controller_frequency: 1.0
controller_patience: 15.0
planner_frequency: 0.0

QuadGapPlannerROS:
  ########
  # Goal #
  ########
  xy_global_goal_tolerance: 0.25
  yaw_global_goal_tolerance: 6.28
  xy_waypoint_tolerance: 0.1

  ################
  # PlanningMode #
  ################
  holonomic: True
  heading: True
  projection_operator: True
  robot_path_orient_linear_decay: True
  virtual_path_decay_enable: True
  decay_factor: 0.0
  use_bezier: True

  #################
  # ControlParams #
  #################
  Kpx: 2
  Kpy: 2
  Kpz: 0.8
  ctrl_ahead_pose: 2

  #################
  # ManualControl #
  #################
  man_ctrl: False
  man_x: 0.0
  man_y: 0.0
  man_theta: 0.0
  line: False

  ###################
  # GapManipulation #
  ###################
  rot_ratio: 1.5
  reduction_threshold: 3.1415926
  reduction_target: 1.5707
  radial_extend: True
  radial_convert: True

  ###################
  # ProjectionParam #
  ###################
  k_po_x: 1.0
  r_unity: 0.35
  r_zero: 1.0

  ##############
  # Trajectory #
  ##############
  integrate_maxt: 10
  integrate_stept: 0.5
  rmax: 0.5
  sigma: 0.3
  inf_ratio: 1.2
  Q: 1
  pen_exp_weight: 3
  Q_f: 10
  robot_geo_scale: 1
  bezier_interp: True
  bezier_unit_time: 0.1
  bezier_num_sampled_pts: 10

  ####################
  # CollisionChecker #
  ####################
  collision_checker_enable: False
  cc_type: 1

  # min_resoln: 1
  # gap_diff: 0.1
  # global_plan_lookup_increment: 30

  # global_plan_change_tolerance: 0.1
  # follow_the_gap_vis: False
  # close_gap_vis: False
  # debug_viz: True

  # epsilon2: 0.20 # 0.18 0.09
  # epsilon1: 0.20 # 0.18 0.09
  # r_inscr:  0.20


  # niGen_s: True
  # config_sanity_val: 100

  # viz_jitter: 0.01

  # waypoint_ratio: 1.5

  # feasi_inflated: True
  # projection_inflated: True
  # far_feasible: True

  # fig_gen: False

  # full_fov: False

  # synthesized_frame: True
  # scale: 1