DynamicGapPlanner:

# params are from https://github.com/dietriro/rto_core/tree/noetic-devel/rto_navigation/config
# and https://www.robotshop.com/media/files/content/f/fto/pdf/festo-robotino-mobile-robotic-datasheet.pdf

# Trajectory
# max_samples: 500
# allow_init_with_backwards_motion: false
# max_global_plan_lookahead_dist: 5.6
# global_plan_viapoint_sep: -1
# global_plan_prune_distance: 1
# exact_arc_length: false
# publish_feedback: false

# Robot

max_vel_x: 2.78
max_vel_x_backwards: 2.78
max_vel_y: 2.78
max_vel_theta: 1.0
acc_lim_x: 2.5
acc_lim_theta: 3.2
min_turning_radius: 0.0 # diff-drive robot (can turn on place!)
max_range: 5.6 # m
robot_radius: 0.225 # m

footprint_model:
  type: point

# Agents
agent_radius: 0.30 # m (guess)

# GoalTolerance

