DwaLocalPlannerROS:

  odom_topic: odom

  # params are from https://github.com/dietriro/rto_core/tree/noetic-devel/rto_navigation/config
  # and https://www.robotshop.com/media/files/content/f/fto/pdf/festo-robotino-mobile-robotic-datasheet.pdf

  # Robot Configuration Parameters
  max_vel_x: 0.0
  min_vel_x: 0.0

  max_vel_y: 0.0
  min_vel_y: 0.0

  # The velocity when robot is moving in a straight line
  max_vel_trans: 0.0
  min_vel_trans: 0.0

  max_vel_theta: 0.0
  min_vel_theta: 0.0

  acc_lim_x: 0.0
  acc_lim_theta: 0.0

  # Goal Tolerance Parametes
  xy_goal_tolerance: 0.25
  yaw_goal_tolerance: 6.28